#!/bin/bash


#ansible-playbook ${PLAYBOOK_FILE:-playbooks/openshift-checks/certificate_expiry/easy-mode-upload.yaml}
set -x

/usr/local/bin/run $@

cat  /tmp/cert-expiry-report.json

#EXPIRE_CERT=$(jq '.summary.expired' /tmp/cert-expiry-report.json)
#domain=$(grep -w -A2 DNS /tmp/cert-expiry-report.json  | cut -d '=' -f2 | tail -n3 | head -n1| cut -d ',' -f1)
#text="$domain certificate - expired"
#
#if [ $EXPIRE_CERT -ge 0 ]
#then
#    webhook_url=${1}
#    channel=${1:-#integrationtests}
#    json="{\"channel\": \"${channel}\", \"username\":\"certificates\", \"icon_emoji\":\":scream_cat:\", \"attachments\":[{\"color\":\"danger\" , \"text\": \"$text\"}]}"
#    curl -X POST --data-urlencode  "payload=$json" "$webhook_url"
#fi
