#!/bin/bash

if ! grep -q 'localhost ansible_become=false' $INVENTORY_FILE; then
    cat - $INVENTORY_FILE >/tmp/hosts <<<"localhost ansible_become=false"
    export INVENTORY_FILE=/tmp/hosts
fi

/usr/local/bin/run $@

TOTAL=$(jq .summary.total /tmp/cert-expiry-report.json || echo -1)
WARNING=$(jq .summary.warning /tmp/cert-expiry-report.json || echo -1)
EXPIRED=$(jq .summary.expired /tmp/cert-expiry-report.json || echo -1)

echo "-- Report start --"
jq . /tmp/cert-expiry-report.json
echo "-- Report end --"

if (( TOTAL < 0 || WARNING < 0 || EXPIRED < 0 )); then
    event "ERROR"
    exit 1
fi

if (( WARNING > 0 )); then
    echo WARNING $WARNING
fi

if (( EXPIRED > 0 )); then
    echo CRITICAL $EXPIRED
fi
